name = "Cozy RPG Pack"
author = "Dylan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d312119dcb7f7e9e27cc967a11df69ff7d9c7d413a6e505e319d28b79537d002"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
