name = "Cozy RPG Pack"
author = "Dylan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0696a8c2e1efbbeee0c0eaba04f110de90dd63a359dc457e0450a8f00285597"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
