name = "Cozy RPG Pack"
author = "Dylan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12d18cd753a827f46a63d8a241d194c6f986c2ac924848caebd28f08f0df3c11"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
