"""Old-era chunk finder: python tools/seams/compare.py <live_world> <fresh_world> <out_dir> x,z [x,z ...]
<fresh_world> is the same seed regenerated with the current pack (test server). Per chunk it compares the stored 3D
biomes (building doesn't change them) and the surface heights. Chunks whose biomes disagree were generated by an
older version of the pack; those are the ones to regenerate. Renders live | fresh | mismatch side by side."""
import os, sys
from PIL import Image, ImageDraw
import anvil
from biomes import cell_biomes, biome_colour, R, PX
from survey import load


def biome_cells(chunk):
    at = cell_biomes(chunk)
    ys = sorted(s["Y"] for s in chunk.get("sections", []) if s.get("biomes"))
    return {(qx, y, qz): at(qx, y, qz) for y in range(ys[0] * 16, ys[-1] * 16 + 16, 4) for qz in range(4) for qx in range(4)} if ys else {}


def compare(live, fresh, out, x, z):
    ccx, ccz = x >> 4, z >> 4
    n = 2 * R + 1
    w = n * 16 * PX
    img = Image.new("RGB", (w * 3 + 20, w), (20, 20, 20))
    d = ImageDraw.Draw(img)
    lc, fc, old = {}, {}, []
    for cx in range(ccx - R, ccx + R + 1):
        for cz in range(ccz - R, ccz + R + 1):
            a, b = load(live, cx, cz, lc), load(fresh, cx, cz, fc)
            if a is None or b is None:
                continue
            ca, cb = biome_cells(a), biome_cells(b)
            keys = ca.keys() & cb.keys()
            diff = sum(ca[k] != cb[k] for k in keys) / max(1, len(keys))
            ha = anvil.heightmap(a, "OCEAN_FLOOR") or anvil.heightmap(a)
            hb = anvil.heightmap(b, "OCEAN_FLOOR") or anvil.heightmap(b)
            hdiff = sum(abs(ha[i][j] - hb[i][j]) for i in range(16) for j in range(16)) / 256 if ha and hb else 0
            ox, oz = (cx - ccx + R) * 16 * PX, (cz - ccz + R) * 16 * PX
            for panel, chunk in ((0, a), (1, b)):
                at = cell_biomes(chunk)
                hm = anvil.heightmap(chunk, "MOTION_BLOCKING_NO_LEAVES") or anvil.heightmap(chunk)
                for qz in range(4):
                    for qx in range(4):
                        y = hm[qz * 4 + 2][qx * 4 + 2] - 1 if hm else 64
                        px = panel * (w + 10) + ox + qx * 4 * PX
                        d.rectangle([px, oz + qz * 4 * PX, px + 4 * PX - 1, oz + (qz + 1) * 4 * PX - 1],
                                    fill=biome_colour(at(qx, y, qz) or "?"))
            bad = diff > 0.05
            col = (220, 40, 40) if bad else (40, 160, 60) if hdiff < 3 else (200, 170, 40)
            d.rectangle([2 * (w + 10) + ox, oz, 2 * (w + 10) + ox + 16 * PX - 2, oz + 16 * PX - 2], fill=col)
            if bad:
                old.append(((cx, cz), round(diff, 2), round(hdiff, 1)))
    for p in range(3):
        for i in range(n + 1):
            d.line([p * (w + 10) + i * 16 * PX, 0, p * (w + 10) + i * 16 * PX, w], fill=(40, 40, 40))
            d.line([p * (w + 10), i * 16 * PX, p * (w + 10) + w, i * 16 * PX], fill=(40, 40, 40))
        sx, sz = p * (w + 10) + (x - (ccx - R) * 16) * PX, (z - (ccz - R) * 16) * PX
        d.ellipse([sx - 6, sz - 6, sx + 6, sz + 6], outline=(0, 0, 0), width=3)
    path = os.path.join(out, f"compare_{x}_{z}.png")
    img.save(path)
    print(f"== {x},{z}: {len(old)} old-era chunks  {os.path.basename(path)}")
    print("   " + " ".join(f"{c[0]},{c[1]}" for c, _, _ in sorted(old)))
    return [c for c, _, _ in old]


if __name__ == "__main__":
    live, fresh, out = sys.argv[1:4]
    os.makedirs(out, exist_ok=True)
    for arg in sys.argv[4:]:
        x, z = (int(v) for v in arg.split(","))
        compare(live, fresh, out, x, z)
